//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairlyInspection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comPerson
    {
        public string HrmOrgId { get; set; }
        public string SalCompanyId { get; set; }
        public string PersonId { get; set; }
        public string GroupId { get; set; }
        public string BelongOrgId { get; set; }
        public string DeptId { get; set; }
        public string BelongGroupId { get; set; }
        public string ServiceStatus { get; set; }
        public string PostOrgId { get; set; }
        public string PostId { get; set; }
        public string PositionId { get; set; }
        public string OfficePhone { get; set; }
        public string Ext { get; set; }
        public string Office { get; set; }
        public int InductionDate { get; set; }
        public short Probation { get; set; }
        public int FormalDate { get; set; }
        public int BandhDate { get; set; }
        public int RestorationDate { get; set; }
        public int DimissionDate { get; set; }
        public string CreatorId { get; set; }
        public long CreateTime { get; set; }
        public string LastOperatorId { get; set; }
        public long LastOperateTime { get; set; }
        public string Remark { get; set; }
        public short AttachementCount { get; set; }
        public long InternalId { get; set; }
        public bool HasPostil { get; set; }
        public short TimesPrinted { get; set; }
        public short TimesEmailSend { get; set; }
        public short TimesExported { get; set; }
        public string PermitterId { get; set; }
        public long PermitTime { get; set; }
        public byte PermitState { get; set; }
        public byte FlowState { get; set; }
        public byte VaryState { get; set; }
        public byte MergeOutState { get; set; }
        public bool IsInUsed { get; set; }
        public string AuthorizedId { get; set; }
        public byte CurrentState { get; set; }
        public string MnemonicId { get; set; }
        public string PositionGradeId { get; set; }
        public string PositionLevelId { get; set; }
        public string SalaryMethodId { get; set; }
        public string SalaryModeId { get; set; }
        public int BeginWorkDate { get; set; }
        public int WorkMonths { get; set; }
        public bool IsOpeningData { get; set; }
        public bool IsRedeployed { get; set; }
        public bool IsRealOpeningData { get; set; }
        public int ValidityFromDate { get; set; }
        public int ValidityToDate { get; set; }
        public int ComWorkMonths { get; set; }
        public int FirstInductionDate { get; set; }
        public string CostCompanyId { get; set; }
        public string InsurCompanyId { get; set; }
        public byte InsurType { get; set; }
        public string UpdateKey { get; set; }
        public string ContractCompId { get; set; }
        public int PreFormalDate { get; set; }
        public string InsurCityId { get; set; }
        public int ContractBeginDate { get; set; }
        public int ContractPeriod { get; set; }
        public int ContractEndDate { get; set; }
        public string FlowDept { get; set; }
        public string CostCenterId { get; set; }
        public byte IDKind { get; set; }
        public string IDNo { get; set; }
        public int IDValidityFromDate { get; set; }
        public int IDValidityToDate { get; set; }
        public bool IsContainDesign { get; set; }
        public string AttScopeId { get; set; }
        public string SalScopeId { get; set; }
        public bool IsNotIncludeNums { get; set; }
        public string PayCompanyId { get; set; }
        public byte PayType { get; set; }
        public byte ContractType { get; set; }
        public Nullable<bool> IsPigeonhole_RENAME { get; set; }
        public byte[] PigeonholeConditionInfo { get; set; }
        public string PersonTypeId { get; set; }
        public byte IsPigeonhole { get; set; }
        public int WorkAge { get; set; }
        public int FromSourceTag { get; set; }
        public string FromBillNo { get; set; }
        public int FromRowCode { get; set; }
        public byte ContractState { get; set; }
        public int ExpiryDate { get; set; }
        public int SignCount { get; set; }
        public byte PeriodKind { get; set; }
        public string WorkCityId { get; set; }
    }
}
