//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairlyInspection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemLogs
    {
        public int ID { get; set; }
        public int ItemID { get; set; }
        public int ItemSystem { get; set; }
        public string ItemTitle { get; set; }
        public int Level { get; set; }
        public int CheckResult { get; set; }
        public string MainPic { get; set; }
        public string Description { get; set; }
        public bool IsLatest { get; set; }
        public System.DateTime NextCheckDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int Creater { get; set; }
    }
}
