//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairlyInspection.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class T8ERPEntities : DbContext
    {
        public T8ERPEntities()
            : base("name=T8ERPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<comDepartment> comDepartment { get; set; }
        public virtual DbSet<comGroupPerson> comGroupPerson { get; set; }
        public virtual DbSet<comPerson> comPerson { get; set; }
    }
}
