//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairlyInspectionNotify.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comGroupPerson
    {
        public string PersonId { get; set; }
        public string PersonName { get; set; }
        public byte MarriedStatus { get; set; }
        public int BloodType { get; set; }
        public int Birthday { get; set; }
        public byte Sex { get; set; }
        public string EverName { get; set; }
        public string NickName { get; set; }
        public int ShengXiao { get; set; }
        public int Constellation { get; set; }
        public string Phone { get; set; }
        public string HomePhone { get; set; }
        public string MSNNo { get; set; }
        public string QQNo { get; set; }
        public string EMail { get; set; }
        public string CreatorId { get; set; }
        public long CreateTime { get; set; }
        public string LastOperatorId { get; set; }
        public long LastOperateTime { get; set; }
        public string Remark { get; set; }
        public short AttachementCount { get; set; }
        public long InternalId { get; set; }
        public bool HasPostil { get; set; }
        public short TimesPrinted { get; set; }
        public short TimesEmailSend { get; set; }
        public short TimesExported { get; set; }
        public string PermitterId { get; set; }
        public long PermitTime { get; set; }
        public byte PermitState { get; set; }
        public byte FlowState { get; set; }
        public byte VaryState { get; set; }
        public byte MergeOutState { get; set; }
        public string AuthorizedId { get; set; }
        public byte CurrentState { get; set; }
        public bool IsInUsed { get; set; }
        public string MnemonicId { get; set; }
        public string IDAwardOrg { get; set; }
        public string IDPlace { get; set; }
        public int Anniversary { get; set; }
        public string CountryId { get; set; }
        public string OrigHomeplace { get; set; }
        public string NationId { get; set; }
        public string PoliticsStatusId { get; set; }
        public string EngName { get; set; }
        public string Homeplace { get; set; }
        public short MilitaryService { get; set; }
        public short Stature { get; set; }
        public float Weight { get; set; }
        public string Hobby { get; set; }
        public string Abhorrer { get; set; }
        public string Speciality { get; set; }
        public string MiniBlog { get; set; }
        public byte IsSmoker { get; set; }
        public int BodyCheckCyc { get; set; }
        public int LastBodyCheckDate { get; set; }
        public string OtherSkill { get; set; }
        public string Character { get; set; }
        public string AutoAnalysis { get; set; }
        public float LeftEyesight { get; set; }
        public float RightEyesignt { get; set; }
        public string EyeState { get; set; }
        public string DiffColor { get; set; }
        public string Fax { get; set; }
        public string Password { get; set; }
        public string UpdateKey { get; set; }
        public bool IsBlackList { get; set; }
        public string PMail { get; set; }
        public string HighestEduId { get; set; }
        public string SpecialityId { get; set; }
        public string LINE { get; set; }
    }
}
