//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairlyInspectionNotify.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InspectionEntities : DbContext
    {
        public InspectionEntities()
            : base("name=InspectionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Interlock> Interlock { get; set; }
        public virtual DbSet<ItemAssign> ItemAssign { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<ItemLogs> ItemLogs { get; set; }
        public virtual DbSet<SendSequence> SendSequence { get; set; }
        public virtual DbSet<CheckingInspectors> CheckingInspectors { get; set; }
        public virtual DbSet<CheckingItem> CheckingItem { get; set; }
        public virtual DbSet<CheckingItemLog> CheckingItemLog { get; set; }
        public virtual DbSet<CheckingItemLogsImage> CheckingItemLogsImage { get; set; }
        public virtual DbSet<CheckingPath> CheckingPath { get; set; }
        public virtual DbSet<CheckingPathLog> CheckingPathLog { get; set; }
        public virtual DbSet<CheckingPoint> CheckingPoint { get; set; }
        public virtual DbSet<CheckingPointLog> CheckingPointLog { get; set; }
        public virtual DbSet<ItemLogsImage> ItemLogsImage { get; set; }
    }
}
